server:
  port: 9090

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    server:
      wait-time-in-ms-when-sync-empty: 0
    serviceUrl:
      defaultZone: http://eureka:9090/eureka
  instance:
    preferIpAddress: true

spring:
  application:
    name: xotomicro-back-eureka-server

logging:
  level:
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN
